apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::254130442659:role/eks_cluster
      username: eks-cluster-role
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::254130442659:user/admin_k8s
      username: admin_k8s
      groups:
        - system:masters
  mapAccounts: |
    - "254130442659"
